modLoader="javafml"
loaderVersion="[47,)"
license="none"

[[mods]]
modId="innofixes"
version="${file.jarVersion}"
displayName="InnoFixes"
authors="baffledhedgehog"
description='''Моё тело это машина превращающая баги в ещё больше багов'''

[[dependencies.innofixes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.innofixes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.innofixes]]
modId="artifacts"
mandatory=true
versionRange="[9.5.16,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="relics"
mandatory=true
versionRange="[0.8.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="attributeslib"
mandatory=true
versionRange="[1.3.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="apotheosis"
mandatory=true
versionRange="[7.4.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="tconstruct"
mandatory=true
versionRange="[3.11.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="mna"
mandatory=true
versionRange="[3.1.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="chunkloaders"
mandatory=true
versionRange="[1.2.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="innoadditions"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="mna_attrib_apoth"
mandatory=true
versionRange="[0.5-1.20.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="integrateddynamics"
mandatory=true
versionRange="[1.29.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="vschunkloader"
mandatory=true
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="waystones"
mandatory=true
versionRange="[14.1.18,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="asynclocator"
mandatory=true
versionRange="[1.3.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.innofixes]]
modId="fzzy_config"
mandatory=true
versionRange="[0.7.5,)"
ordering="AFTER"
side="BOTH"
